version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
  assignees:
  - dciborow
  allow:
  - dependency-type: direct
  - dependency-type: indirect
  commit-message:
    prefix: "fix: "
