import contextlib
import typing as T

def get_process_index(local=False) -> int: ...
def get_process_count() -> int: ...
def check_main_process(local=False) -> bool: ...
def check_debug_enabled() -> bool: ...
def barrier() -> None: ...
@contextlib.contextmanager
def main_process_first() -> T.Generator[None, T.Any, None]: ...
@contextlib.contextmanager
def local_main_process_first() -> T.Generator[None, T.Any, None]: ...
