name: Python CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    types: [created]    
  workflow_dispatch:

jobs:
  validation:
    uses: microsoft/action-python/.github/workflows/validation.yml@0.3.9
    with:
      workdir: sources
      testdir: sources

  publish:
    uses: microsoft/action-python/.github/workflows/publish.yml@0.3.9
    secrets:
      PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      TEST_PYPI_PASSWORD: ${{ secrets.TEST_PYPI_PASSWORD  }}
